---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: portworx-shared-sc
provisioner: kubernetes.io/portworx-volume
parameters:
 repl: "1"
 priority_io: "high"
 sharedv4: "true"
 allow_others: "true"
allowVolumeExpansion: true
volumeBindingMode: Immediate

#Couch db
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: portworx-couchdb-sc
provisioner: kubernetes.io/portworx-volume
parameters:
 repl: "3"
 priority_io: "high"
 io_profile: "db_remote"
 disable_io_profile_protection: "1"
allowVolumeExpansion: true

#Elastic Search:
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: portworx-elastic-sc
provisioner: kubernetes.io/portworx-volume
parameters:
 repl: "3"
 priority_io: "high"
 io_profile: "db_remote"
 disable_io_profile_protection: "1"
allowVolumeExpansion: true

#Solr:
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: portworx-solr-sc
provisioner: kubernetes.io/portworx-volume
parameters:
 repl: "3"
 priority_io: "high"
allowVolumeExpansion: true

#Cassandra:
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: portworx-cassandra-sc
provisioner: kubernetes.io/portworx-volume
parameters:
 repl: "3"
 priority_io: "high"
allowVolumeExpansion: true

#Kafka:
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: portworx-kafka-sc
provisioner: kubernetes.io/portworx-volume
parameters:
 repl: "3"
 priority_io: "high"
allowVolumeExpansion: true

#DB2 - WKC:
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: portworx-db2-sc
provisioner: kubernetes.io/portworx-volume
parameters:
 repl: "3"
 priority_io: "high"
 io_profile: "db"
 block_size: "4096b"
 sharedv4: "false"
allowVolumeExpansion: true

# metastoredb:
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-metastoredb-sc
parameters:
  priority_io: high
  io_profile: db
  repl: "3"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

#Shared gp high iops:
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-shared-gp
parameters:
  priority_io: high
  repl: "1"
  sharedv4: "true"
  allow_others: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# shared gp2 throughput optimized
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-shared-gp2
parameters:
  priority_io: high
  repl: "2"
  sharedv4: "true"
  allow_others: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# shared gp3 replica 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-shared-gp3
parameters:
  priority_io: high
  repl: "3"
  sharedv4: "true"
  io_profile: db
  allow_others: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# gp db
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-db-gp
parameters:
  io_profile: "db"
  repl: "1"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# db gp3 replica 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-db-gp3
parameters:
  io_profile: "db"
  repl: "3"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# gp nonshared iops optimized
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-nonshared-gp
parameters:
  priority_io: high
  repl: "1"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# gp2 nonshared throughput optimized
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-nonshared-gp2
parameters:
  priority_io: high
  repl: "1"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# gp3 rwo replica 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: portworx-gp3-sc
parameters:
 priority_io: high
 io_profile: "db_remote"
 repl: "3"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate

# streams
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-shared-gp-allow
parameters:
  priority_io: high
  repl: "1"
  sharedv4: "true"
  io_profile: "cms"
  allow_others: "true"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate



# DB2Wh shared for System Storage, backup storage, future load storage, and future diagnostic logs storage
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-db2-rwx-sc
parameters:
  allow_others: "true"
  block_size: 4096b
  repl: "3"
  sharedv4: "true"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate


# Db2Wh nonshared SC for user storage, future transaction logs storage, future archive/mirrors logs storage
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-db2-rwo-sc
parameters:
  allow_others: "true"
  block_size: 4096b
  io_profile: db
  priority_io: high
  repl: "3"
  sharedv4: "false"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate


# DV
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-dv-shared-gp
parameters:
  block_size: 4096b
  priority_io: high 
  repl: "1"
  shared: "true"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate


# Watson Assistant
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-assistant
parameters:
   repl: "3"
   priority_io: "high"
   io_profile: "db"
   block_size: "64k"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
